"""empty message

Revision ID: 2e23b414a6f1
Revises: 239fa623c368
Create Date: 2020-01-19 08:34:56.942166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e23b414a6f1'
down_revision = '239fa623c368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_picks_closed', table_name='picks')
    op.drop_index('ix_picks_goal', table_name='picks')
    op.drop_index('ix_picks_hours', table_name='picks')
    op.drop_index('ix_picks_student_name', table_name='picks')
    op.drop_index('ix_picks_student_phone', table_name='picks')
    op.drop_index('ix_picks_timestamp', table_name='picks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_picks_timestamp', 'picks', ['timestamp'], unique=False)
    op.create_index('ix_picks_student_phone', 'picks', ['student_phone'], unique=False)
    op.create_index('ix_picks_student_name', 'picks', ['student_name'], unique=False)
    op.create_index('ix_picks_hours', 'picks', ['hours'], unique=False)
    op.create_index('ix_picks_goal', 'picks', ['goal'], unique=False)
    op.create_index('ix_picks_closed', 'picks', ['closed'], unique=False)
    # ### end Alembic commands ###
