"""empty message

Revision ID: 98cca435360e
Revises: 
Create Date: 2020-01-19 20:23:35.700916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98cca435360e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_en', sa.String(length=30), nullable=True),
    sa.Column('text_ru', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text_en'),
    sa.UniqueConstraint('text_ru')
    )
    op.create_table('picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('student_name', sa.String(length=64), nullable=False),
    sa.Column('student_phone', sa.String(length=25), nullable=False),
    sa.Column('goal', sa.String(length=25), nullable=False),
    sa.Column('hours', sa.String(length=5), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('about', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('timetable', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('student_name', sa.String(length=64), nullable=True),
    sa.Column('student_phone', sa.String(length=25), nullable=True),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_closed'), 'bookings', ['closed'], unique=False)
    op.create_index(op.f('ix_bookings_date_time'), 'bookings', ['date_time'], unique=False)
    op.create_index(op.f('ix_bookings_student_name'), 'bookings', ['student_name'], unique=False)
    op.create_index(op.f('ix_bookings_student_phone'), 'bookings', ['student_phone'], unique=False)
    op.create_index(op.f('ix_bookings_timestamp'), 'bookings', ['timestamp'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sender_name', sa.String(length=64), nullable=False),
    sa.Column('sender_phone', sa.String(length=25), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('addressee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['addressee_id'], ['tutors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutors_goals',
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutors_goals')
    op.drop_table('messages')
    op.drop_index(op.f('ix_bookings_timestamp'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_student_phone'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_student_name'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_date_time'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_closed'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('tutors')
    op.drop_table('picks')
    op.drop_table('goals')
    # ### end Alembic commands ###
